### ISSUE TITLE
Change "method" to "name" and "options" to "value" in "options" class

### ISSUE THREAD

**Issue by jsadler2** [DavidChoi76/pysumma_alpha#1]
See line https://github.com/DavidChoi76/pysumma_alpha/blob/master/pysumma/pysumma/Decisions.py#L40 for example

**Comment by DavidChoi76** [comment]
[#1] updated this issues https://github.com/DavidChoi76/pysumma_alpha/commit/352b1102595bdf6b82cbc5f5028103f3dbf039c3
