### ISSUE TITLE
Choice validation

### ISSUE THREAD

**Issue by jsadler2** [DavidChoi76/pysumma_alpha#3]
When values are set in an `options` object, the entered value should be validated against the objects `options` attributes. For example:
```python
>>>d = Decisions(file_name, path)
>>>d.soilCatTbl = 'banana'
```
Should return an exception

**Comment by DavidChoi76** [comment]
add choice validation https://github.com/DavidChoi76/pysumma_alpha/commit/352b1102595bdf6b82cbc5f5028103f3dbf039c3
